# Generated by Django 4.2.5 on 2023-10-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='basket',
            field=models.TextField(verbose_name='Корзина товаров'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Фамилия клиента'),
        ),
    ]
